### ISSUE TITLE
Where is the fault cause i can't find it

### ISSUE THREAD

**Issue by dwd010** [0l1v3rr/discordjs-ticket-bot#1]
 node index.js
/home/runner/bbystickets/node_modules/discord.js/src/rest/RESTManager.js:32
    const token = this.client.token ?? this.client.accessToken;
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/bbystickets/node_modules/discord.js/src/client/BaseClient.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
exit status 1

**Comment by 0l1v3rr** [comment]
Hi, I think you use an older Node.js version, which does not support the nullish coalescing operator (??). Check your Node.js version by typing this command: node --version
You can read more about that here: https://stackoverflow.com/questions/68730332/unexpected-token-discord-js
